# -*- coding: utf-8 -*-
"""арабизатор без хамзы

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rBOhPJer4OSV9W0NJyqqdphruYeOyds7
"""

#этот код РАБОТАЕТ, туда нужно добавить правила хамзы и все

arabic_alphabet = {
    'ā':'َا', 'ū':'ُو', 'ī':'ِي', 'b':'ب', 't':'ت', 'ṯ':'ث', 'ǯ':'ج', 'ḥ':'ح', 'ḫ':'خ', 'd':'د', 'ḏ':'ذ', 'r':'ر', 'z':'ز', 's':'س', 'š':'ش',
    'ṣ':'ص',  'ḍ':'ض', 'ṭ':'ط', 'ḏ̣':'ظ', 'ˁ':'ع', 'ġ':'غ', 'f':'ف', 'q':'ق', 'k':'ك', 'l':'ل', 'm':'م', 'n':'ن', 'h':'ه', 'w':'و', 'y':'ي',
    'a':'َ', 'i':'ِ', 'u':'ُ', ' ':' ', ',':',', '.':'.', ':':':', ';':';', '-':'-', 'ˀ':'ء'
}

def TurnIntoArabic(word):
    word = list(word)
    ar_word = list()
    for i in word:
        ar_word.append(arabic_alphabet[i])
    for i in range(len(ar_word) - 1):
        if ar_word[i] == ar_word[i + 1]:
          ar_word[i + 1] = 'ّ'
    if ar_word[len(ar_word) - 1] == 'ن' and ar_word[len(ar_word) - 2] == 'َ':
        ar_word[len(ar_word) - 1] = 'ً'
        ar_word[len(ar_word) - 2] = 'ا'
    elif ar_word[len(ar_word) - 1] == 'ن' and ar_word[len(ar_word) - 2] == 'ُ':
        ar_word[len(ar_word) - 1] = 'ٌ'
        ar_word[len(ar_word) - 2] = ''
    elif ar_word[len(ar_word) - 1] == 'ن' and ar_word[len(ar_word) - 2] == 'ِ':
        ar_word[len(ar_word) - 1] = 'ٍ'
        ar_word[len(ar_word) - 2] = ''

    return ''.join(ar_word)
#print(TurnIntoArabic(word=input()))

latin_alphabet = {v:k for k, v in arabic_alphabet.items()}

def TurnIntoLatin(word):
    word = list(word)
    latin_word = list()
    for i in range(len(word) - 1):
        if word[i + 1] == 'ّ':
            word[i + 1] = word[i]
    if word[len(word) - 1] == 'ٌ':
        word[len(word) - 1] = 'ُ'
        word.append('ن')
    elif word[len(word) - 1] == 'ٍ':
        word[len(word) - 1] = 'ِ'
        word.append('ن')
    elif word[len(word) - 2] == 'ً' and word[len(word) - 1] == 'ا':
        word[len(word) - 2] = 'َ'
        word[len(word) - 1]('ن')
    for i in word:
        latin_word.append(latin_alphabet[i])
    return ''.join(latin_word)
print(TurnIntoLatin(word=input()))

